### ISSUE TITLE
Maybe move the gif outside the repo?

### ISSUE THREAD

**Issue by metalelf0** [caenrique/nvim-maximize-window-toggle#1]
Hi man, first of all: great idea, loving your plugin so far. I only have one suggestion: maybe moving the gif outside the repo would be a better experience when first installing the plugin. Having a 34 MB repo, when the actual plugin code is 30 lines long, is a little too much IMHO ;) Thanks and keep up the great work!

**Comment by caenrique** [comment]
yeah, you are absolutely right. That's done.
Thanks for the suggestion!
